sources:
- name: gitlab
  source: gitlab:mokmail1/chat
  kb-id: f70b3c8f-ba98-42a6-8c22-2a8610cce337
  filter:
    include:
    - '*.md'
    exclude:
    - frontend
    - backend
    - .env
    - '*.py'
- name: BEV
  source: web:https://bev.gv.at
  kb-id: f70b3c8f-ba98-42a6-8c22-2a8610cce337
